### ISSUE TITLE
Question-Box: Iterate upon design

### ISSUE THREAD

**Issue by Wegi** [schnaq/schnaq#105]
The design right now is functional, but not iterated upon, to make it shine and be beautifull.

Take a few hours and improve upon it. The functionality is all there after PR #104

**Comment by birkhoff** [comment]
Adminsicht:
<img width="959" alt="image" src="https://github.com/schnaq/schnaq/assets/1282120/358a3492-7a36-4e5f-a30a-6fc1395c5d6d">


Nutzersicht:

<img width="365" alt="image" src="https://github.com/schnaq/schnaq/assets/1282120/04d0377e-8e46-4490-b191-62fab833b3b5">

- Die Pillen in der Nutzersicht sind oben aligned
- Die Icon-Buttons für Admins sind oben aligned mit dem selben vertikalen Padding, den die Inhalte der Fragebox haben
