### ISSUE TITLE
Analytics view throws "linear" not registered scale error

### ISSUE THREAD

**Issue by Wegi** [schnaq/schnaq#64]
Analytics view is broken and does not render. Probably because of an update of chart.js. See screenshot for error message.

<img width="1435" alt="Bildschirm­foto 2023-01-09 um 09 10 20" src="https://user-images.githubusercontent.com/1516122/211264318-b0baf90b-8f4b-4c81-9e5e-43a6097a200f.png">

**Comment by Wegi** [comment]
It seems that this only happens in the production environment for some reason. Needs some more investigation.

**Comment by n2o** [comment]
Fixed
