### ISSUE TITLE
Wörter in Wortwolke überschneiden sich

### ISSUE THREAD

**Issue by birkhoff** [schnaq/schnaq#65]
Längere Wörter überschneiden sich in der Wortwolke

![image](https://user-images.githubusercontent.com/1282120/211305166-7a3be842-4528-4e79-98f4-0c1f7b227124.png)

**Comment by Wegi** [comment]
Not possible to reproduce right now, please reopen with more examples, should this happen again.

**Comment by n2o** [comment]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/1507474/216580375-c5a20f3f-76b1-4afc-bf7d-95f4dd03fa26.png">
