### ISSUE TITLE
Feedback-Form: Backend Model and API Routes

### ISSUE THREAD

**Issue by n2o** [schnaq/schnaq#73]
Add a backend model to store the feedback forms. Required fields (maybe there are adjustments necessary):

- `:discussion/feedback`: A reference to the feedback-form entity

Feedback Form Entity:

- `:feedback/items`: A collection of feedback items
- `:feedback.item/label`: A label for the input field for the user
- `:feedback.item/ordinal`: Number representing the position in the feedback form of this specific item
- `:feedback.item/type`: Specify the item's type, currently `:feedback.item.type/text` or `:feedback.item.type/scale-five`
- `:feedback/answers: Collection of answers to a form
- `:feedback.answer/item`: Refer to the item, which is answered (e.g. question 1)
- `:feedback.answer/value`: The actual answer (I am not happy with `value` here. Maybe you have a better idea)

- [x] Define Model
- [x] Add corresponding specs
- [x] Add corresponding patterns
- [x] Add API routes
  - [x] `/discussion/feedback/form`
    - [x] POST: Body contains `share-hash` and the form to which the feedback form is being created
    - [x] PUT: Replace a specific field in the existing form. Needs share-hash
    - [x] DELETE: Delete a form, add the share-hash to the body
  - [x] `/discussion/feedback`
    - [x] GET: Get the current form fields for a user, so that she can participate
    - [x] POST: Participate in the poll and store the answers of the user
  - [x] `/discussion/feedback/results`
    - [x] GET: Show results of a form

**Comment by Wegi** [comment]
Also a route for toggling the visibility

**Comment by n2o** [comment]
Isn't this also just a PUT on the existing resource?
