### ISSUE TITLE
Last-added schnaq can not always be loaded

### ISSUE THREAD

**Issue by Wegi** [schnaq/schnaq#81]
Causes an internal error, when the last-added schnaq is loaded, after it has been deleted. (This happens every time in the schnaq overview for example)

A simple fix would be to delete the last-created hash in the localhost, when the function returns an error.

**Comment by n2o** [comment]
Do you mean an error in the JS Console or where does this error occur?

**Comment by Wegi** [comment]
When you create a schnaq, then delete it, you will get this error in the console (and backend, since the share-hash is not valid), when you open the schnaq overview. 

The last visited schnaq is always loaded for the quick access via the button on the left side.

**Comment by Wegi** [comment]
The error lasts, until you create the next schnaq, I should add.

**Comment by n2o** [comment]
👍
