### ISSUE TITLE
QuestionBox: Create backend routes

### ISSUE THREAD

**Issue by n2o** [schnaq/schnaq#90]
We want to collect questions from the users and answer them OTR, e.g. in real-life, during a live discussion or anywhere else. Just collect questions and answer them somewhere else.

Questions can be marked as answered by moderators. So an answer is only a text and a boolean indicating the answered-status.

It should be possible to create multiple QuestionBoxes per schnaq.

Add routes:

- to GET all questionboxes for a schnaq with their questions
- to GET a single questionbox with their questions
- to DELETE a single questionbox
- to DELETE a question from the questionbox
- to PATCH a question as answered

Edit @Wegi :
- to POST an upvote for a question
- to POST a new questionbox
- to PUT an update to a questionbox (label or visibility)

**Comment by n2o** [comment]
Do question boxes have a title? Or are they just boxes to throw questions in? @Wegi @birkhoff

**Comment by Wegi** [comment]
I think an optional label should be fine. This way multiple boxes are able to be organized.
